using System.ComponentModel;

namespace Skaar.VehicleData.Model.Geographic;

public enum Country
{
    Undefined = 0,

    [IsoCountryCode("ZA")] [Description("South Africa")] SouthAfrica,
    [IsoCountryCode("EG")] Egypt,
    [IsoCountryCode("MA")] Morocco,
    [IsoCountryCode("ZW")] Zimbabwe,
    [IsoCountryCode("BW")] Botswana,
    [IsoCountryCode("AO")] Angola,
    [IsoCountryCode("KE")] Kenya,
    [IsoCountryCode("TN")] Tunisia,
    [IsoCountryCode("NG")] Nigeria,
    [IsoCountryCode("CI")] [Description("Côte d'Ivoire")] IvoryCoast,
    [IsoCountryCode("ET")] Ethiopia,
    [IsoCountryCode("MZ")] Mozambique,
    [IsoCountryCode("MG")] Madagascar,

    [IsoCountryCode("JP")] Japan,
    [IsoCountryCode("IL")] Israel,
    [IsoCountryCode("IN")] India,
    [IsoCountryCode("ID")] Indonesia,
    [IsoCountryCode("CN")] China,
    [IsoCountryCode("PH")] Philippines,
    [IsoCountryCode("TH")] Thailand,
    [IsoCountryCode("MY")] Malaysia,
    [IsoCountryCode("IR")] [Description("Iran (Islamic Republic of)")] Iran,
    [IsoCountryCode("PK")] Pakistan,
    [IsoCountryCode("TR")] Turkey,
    [IsoCountryCode("SA")] [Description("Saudi Arabia")] SaudiArabia,
    [IsoCountryCode("AE")] [Description("United Arab Emirates")] UnitedArabEmirates,
    [IsoCountryCode("TW")] [Description("Taiwan, Province of China")] Taiwan,
    [IsoCountryCode("VN")] [Description("Viet Nam")] Vietnam,
    [IsoCountryCode("SG")] Singapore,
    [IsoCountryCode("HK")] [Description("Hong Kong")] HongKong,

    [IsoCountryCode("RU")] [Description("Russian Federation")] Russia,
    [IsoCountryCode("KZ")] Kazakhstan,
    [IsoCountryCode("UZ")] Uzbekistan,
    [IsoCountryCode("UA")] Ukraine,
    [IsoCountryCode("BY")] Belarus,
    [IsoCountryCode("GE")] Georgia,
    [IsoCountryCode("AM")] Armenia,
    [IsoCountryCode("AZ")] Azerbaijan,
    [IsoCountryCode("KG")] Kyrgyzstan,
    [IsoCountryCode("TJ")] Tajikistan,

    [IsoCountryCode("EE")] Estonia,
    [IsoCountryCode("LV")] Latvia,
    [IsoCountryCode("LT")] Lithuania,
    [IsoCountryCode("PL")] Poland,
    [IsoCountryCode("CZ")] [Description("Czechia")] CzechRepublic,
    [IsoCountryCode("SK")] Slovakia,
    [IsoCountryCode("HU")] Hungary,
    [IsoCountryCode("DE")] Germany,
    [IsoCountryCode("NL")] Netherlands,
    [IsoCountryCode("BE")] Belgium,
    [IsoCountryCode("FR")] France,
    [IsoCountryCode("ES")] Spain,
    [IsoCountryCode("PT")] Portugal,
    [IsoCountryCode("IT")] Italy,
    [IsoCountryCode("CH")] Switzerland,
    [IsoCountryCode("AT")] Austria,
    [IsoCountryCode("DK")] Denmark,
    [IsoCountryCode("SE")] Sweden,
    [IsoCountryCode("NO")] Norway,
    [IsoCountryCode("FI")] Finland,
    [IsoCountryCode("GB")] [Description("United Kingdom")] UnitedKingdom,
    [IsoCountryCode("IE")] Ireland,
    [IsoCountryCode("RO")] Romania,
    [IsoCountryCode("BG")] Bulgaria,
    [IsoCountryCode("RS")] Serbia,
    [IsoCountryCode("HR")] Croatia,
    [IsoCountryCode("SI")] Slovenia,
    [IsoCountryCode("BA")] [Description("Bosnia and Herzegovina")] BosniaHerzegovina,
    [IsoCountryCode("MK")] [Description("North Macedonia")] Macedonia,
    [IsoCountryCode("GR")] Greece,
    [IsoCountryCode("LU")] Luxembourg,
    [IsoCountryCode("AD")] Andorra,
    [IsoCountryCode("SM")] [Description("San Marino")] SanMarino,
    [IsoCountryCode("MT")] Malta,
    [IsoCountryCode("IS")] Iceland,

    [IsoCountryCode("CA")] Canada,
    [IsoCountryCode("US")] [Description("United States")] UnitedStates,
    [IsoCountryCode("MX")] Mexico,
    [IsoCountryCode("DO")] [Description("Dominican Republic")] DominicanRepublic,
    [IsoCountryCode("PR")] [Description("Puerto Rico")] PuertoRico,
    [IsoCountryCode("HN")] Honduras,
    [IsoCountryCode("NI")] Nicaragua,
    [IsoCountryCode("CR")] [Description("Costa Rica")] CostaRica,
    [IsoCountryCode("PA")] Panama,
    [IsoCountryCode("CO")] Colombia,
    [IsoCountryCode("VE")] [Description("Venezuela (Bolivarian Republic of)")] Venezuela,
    [IsoCountryCode("PE")] Peru,
    [IsoCountryCode("BO")] [Description("Bolivia (Plurinational State of)")] Bolivia,
    [IsoCountryCode("CL")] Chile,
    [IsoCountryCode("AR")] Argentina,
    [IsoCountryCode("BR")] Brazil,
    [IsoCountryCode("UY")] Uruguay,

    [IsoCountryCode("AU")] Australia,
    [IsoCountryCode("NZ")] [Description("New Zealand")] NewZealand,

    [IsoCountryCode("LS")] Lesotho,
    [IsoCountryCode("NA")] Namibia,
    [IsoCountryCode("MU")] Mauritius,
    [IsoCountryCode("CY")] Cyprus,
    [IsoCountryCode("RW")] Rwanda,
    [IsoCountryCode("DZ")] Algeria,
    [IsoCountryCode("SZ")] [Description("Eswatini")] Swaziland,
    [IsoCountryCode("UG")] Uganda,
    [IsoCountryCode("LY")] Libya,
    [IsoCountryCode("ZM")] Zambia,

    [IsoCountryCode("KR")] [Description("Korea, Republic of")] SouthKorea,
    [IsoCountryCode("JO")] Jordan,
    [IsoCountryCode("MM")] Myanmar,
    [IsoCountryCode("MN")] Mongolia,
    [IsoCountryCode("IQ")] Iraq,
    [IsoCountryCode("BD")] Bangladesh,
    [IsoCountryCode("LA")] [Description("Lao People's Democratic Republic")] Laos,
    [IsoCountryCode("EC")] Ecuador
}